//POST http://98.84.97.216:8080/api/signup
POST http://localhost:8080/api/patients
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF1ZHlhZHQxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQyMjExOTgwLCJyb2xlIjoiYXVkaW8iLCJ1c2VySWQiOjZ9.-jJaaloj-LhwKTMAWZBDQVQi6cPqpKGaTg5tjgU92HQ

{
  "uhid": "KA-244803029",
  "barcode": "243671063",
  "name": "krishnegowda",
  "labourid": "255363",
  "age": 40,
  "gender": "Male",
  "mobile": "9844658912",
  "district": "Mandya",
  "taluk": "Maddur",
  "camp": "Maradevanahalli(Maddur)"
}
