//POST http://98.84.97.216:8080/api/signup
GET http://98.84.97.216:8080/api/patient/KA-244803029
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvY3lhZHQxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQyNDkxMjYzLCJyb2xlIjoiZG9jdG9yIiwidXNlcklkIjoxfQ.nRHIC51Jt2g1sCFTlZpDsW4hH7RtwLhJmolzj3L0ot8


curl http://98.84.97.216:8080/api/patient/KA-244803029 -H "authorization: "