GET http://localhost:8080/api/admin/campaigns?pageSize=10&page=2
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvY3lhZHQxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQyNjUyNjQ1LCJyb2xlIjoiZG9jdG9yIiwidXNlcklkIjoxfQ.der0W2byVkJg54EKgvIXSJL7DMUW3AhF3z5LWJzMpqI